name: "Build"

on:
  push:
    branches:
      - Juli2022
    

jobs:
  
  MoveSemantic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instal Compiler
        run: sudo apt install g++
      - name: Check Directory
        run: ls
      - name: Check Version Compiler
        run: g++ --version
      - name: Make Bin Folder 
        run: mkdir bin
      - name: check dir
        run: ls
      - name: Make Object File
        run: g++ -c bin/MoveSemantic.o bin/Main.o  src/MoveSemantic.cpp src/Main.cpp
      - name: Compile cpp file
        run: g++ -o bin/MoveSemantic.exe bin/MoveSemantic.o bin/Main.o
      



