name: "Build"

on:
  push:
    branches:
      - Juli2022
    

jobs:
  Singleton:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instal Compiler
        run: sudo apt install g++
      - name: Check Version Compiler
        run: g++ --version
      - name: Check directory
        run: ls
      - name: Compile cpp file
        run: g++ src/Singleton.cpp
      

  MoveSemantic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instal Compiler
        run: sudo apt install g++
      - name: Check Version Compiler
        run: g++ --version
      - name: Compile cpp file
        run: g++ -o MoveSemantic.exe src/Main.cpp src/MoveSemantic.cpp
      - name: Run Executable
        run: ./MoveSemantic.exe



