
on:
  label: 
    types:
      - created
  push:
    branches:
      - Juli2022
jobs:
  job1:
    name: Install Compiler
    runs-on: ubuntu-latest
    steps:
      - run: 
          sudo apt install g++
          g++ --version
     

