name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Compiler
      run:
        sudo apt install g++
    - name: Check Version Compiler
      run:
        g++ --version
    - name: Build CPP File
      run:
       g++ -o /home/runner/work/Learn_Cplusplus/main.exe /home/runner/work/Learn_Cplusplus/src/Main.cpp /home/runner/work/Learn_Cplusplus/Singleton.cpp
    
    - name: Run Executable
      run:
        ${GITHUB_WORKSPACE}/main.exe
    
