name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Compiler
      run:
        sudo apt install g++
    - name: Check Version Compiler
      run:
        g++ --version
    - name: Build CPP File
      run:
        ls
    
    - name: Run Executable
      run:
        ${GITHUB_WORKSPACE}/main.exe
    
